### PR TITLE
fix: export type only `RestEndpointMethodTypes`

### LINKED ISSUE #298: CDN Bug
**Everything was working fine recently** _but today's morning all of a sudden , The project am working on stopped working !_

**Am receiving the following error in the console :-** 
`Uncaught SyntaxError: The requested module '/-/@octokit/plugin-rest-endpoint-methods@v7.1.2-oh7as98dHhwO9RAmSS7b/dist=es2019,mode=imports/optimized/@octokit/plugin-rest-endpoint-methods.js' does not provide an export named 'RestEndpointMethodTypes'`

Can you guide me what should I do to fix this problem.

### PR DESCRIPTION
**Pull request by antfu**
Resolves #298

----

### Before the change?

Reexport of type `RestEndpointMethodTypes` appears in the js dist.

### After the change?

Only re-export it as type.

### Other information

This also breaks Vite when trying to import octokit in the client side. 

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { Octokit as Core } from "@octokit/core";
 import { requestLog } from "@octokit/plugin-request-log";
 import { paginateRest } from "@octokit/plugin-paginate-rest";
 import { legacyRestEndpointMethods } from "@octokit/plugin-rest-endpoint-methods";
-export { RestEndpointMethodTypes } from "@octokit/plugin-rest-endpoint-methods";
+import type { RestEndpointMethodTypes } from "@octokit/plugin-rest-endpoint-methods";
```
Comment (wolfy1339) [inline src/index.ts:5]:
```suggestion
export type { RestEndpointMethodTypes } from "@octokit/plugin-rest-endpoint-methods";
```

File: src/index.ts [hunk 2]
```diff
@@ -15,3 +15,5 @@ export const Octokit = Core.plugin(
 });
 
 export type Octokit = InstanceType<typeof Octokit>;
+export type { RestEndpointMethodTypes };
+
```
Comment (wolfy1339) [inline src/index.ts:19]:
```suggestion
```

**Review by wolfy1339 — CHANGES_REQUESTED** [review]

**Review by wolfy1339 — APPROVED** [review]
